import Head from 'next/head'
import Layout from '@/components/Layout'
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />

      </Head>
      <main className='pt-20 flex text-dark w-full min-h-screen'>
        <Layout>
          <div className="flex items-center justify-between w-full">
            <div className='flex flex-col items-center self-center'>
              <AnimatedText text="Experienced Full Stack Web Developer" className='!text-6xl text-left' />
              <p className='my-4 text-base font-medium'>
              Harness the power of a seasoned full stack web developer with a proven track record. With my expertise in the complete website creation process, I ensure seamless execution from inception to completion, delivering websites that exceed your expectations.
              </p>
              <div className='flex items-center self-start mt-2'>
                <Link target='_blank' href="/AhmadSabbah_Resume.pdf"
                  className='flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark hover:scale-105 transform transition duration-500'
                  download={true}
                >Resume</Link>
                <Link
                  className='flex items-center bg-dark text-light ml-5 p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark hover:scale-105 transform transition duration-500'
                  target='_blank' href="mailto:madesabbah@gmail.com">Contact Me</Link>
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  )
}
